spring:
    datasource:
        url: jdbc:mysql://ed-rds-01.cdgiiabcm6en.us-east-1.rds.amazonaws.com:3306/edwiki?createDatabaseIfNotExist=true
        username: admin
        password: Admin123
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: create
        show-sql: true
        generate-ddl: false
  # Producer properties
    kafka:
        bootstrap-servers: b-1.edkafka01.uin7zi.c13.kafka.us-east-1.amazonaws.com:9092
        group-id: group_id
topic:
  name:
    producer: ed-topic-1 
    consumer: ed-topic-1 
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

#AWS properties
cloud:
    aws:
        region:
            static: us-east-1
        stack:
            auto: false
        credentials:
            accessKey: AKIAYMMFC5FDZJ47HUUA 
            secretKey: 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 

application:
    bucket:
        name: edwiki-webserver-config

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
 
baseUrl: http://app.edshopper.com:5555/v1

