spring:
    datasource:
        url: jdbc:mysql://eos-database-01.cdgiiabcm6en.us-east-1.rds.amazonaws.com:3306/edwiki?createDatabaseIfNotExist=true
        username: admin
        password: admin123
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: create
        show-sql: true
        generate-ddl: false
  # Producer properties
    kafka:
      bootstrap-servers: b-2.eoskafka01.1w38i6.c7.kafka.us-east-1.amazonaws.com:9092
        group-id: group_id
topic:
  name:
    producer: ed-topic-1 
    consumer: ed-topic-1 
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

#AWS properties
cloud:
    aws:
        region:
            static: us-east-1
        stack:
            auto: false
        credentials:
            accessKey: AKIAYMMFC5FDTNAEDS3L 
            secretKey: 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 

application:
    bucket:
        name: eos-catalog-images 

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
 
baseUrl: http://dev-gateway.edshopper.com:5555/v1

